[2024-01-08T08:38:55.013+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: fetching_cleaning.Fetch_from_Postgresql manual__2024-01-08T08:33:51.685602+00:00 [queued]>
[2024-01-08T08:38:55.019+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: fetching_cleaning.Fetch_from_Postgresql manual__2024-01-08T08:33:51.685602+00:00 [queued]>
[2024-01-08T08:38:55.019+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-01-08T08:38:55.019+0000] {taskinstance.py:1369} INFO - Starting attempt 2 of 2
[2024-01-08T08:38:55.019+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-01-08T08:38:55.028+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): Fetch_from_Postgresql> on 2024-01-08 08:33:51.685602+00:00
[2024-01-08T08:38:55.040+0000] {standard_task_runner.py:52} INFO - Started process 276 to run task
[2024-01-08T08:38:55.043+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetching_cleaning', 'Fetch_from_Postgresql', 'manual__2024-01-08T08:33:51.685602+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp6w0ppk46', '--error-file', '/tmp/tmpq_kkpffe']
[2024-01-08T08:38:55.044+0000] {standard_task_runner.py:80} INFO - Job 5: Subtask Fetch_from_Postgresql
[2024-01-08T08:38:55.086+0000] {task_command.py:371} INFO - Running <TaskInstance: fetching_cleaning.Fetch_from_Postgresql manual__2024-01-08T08:33:51.685602+00:00 [running]> on host 13eafc15112b
[2024-01-08T08:38:55.129+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=saepul
AIRFLOW_CTX_DAG_ID=fetching_cleaning
AIRFLOW_CTX_TASK_ID=Fetch_from_Postgresql
AIRFLOW_CTX_EXECUTION_DATE=2024-01-08T08:33:51.685602+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-08T08:33:51.685602+00:00
[2024-01-08T08:38:55.230+0000] {python.py:173} INFO - Done. Returned value was: None
[2024-01-08T08:38:55.239+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=fetching_cleaning, task_id=Fetch_from_Postgresql, execution_date=20240108T083351, start_date=20240108T083855, end_date=20240108T083855
[2024-01-08T08:38:55.303+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-01-08T08:38:55.329+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
